# Generated by Django 3.1.2 on 2021-02-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='event_id',
            field=models.BigIntegerField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
